const ADD_ITEM = "ADD_ITEM";
const CHANGE_SETTING = "CHANGE_SETTING";
const REPLACE_SETTINGS = "REPLACE_SETTINGS";
const INIT_DATA = "INIT_DATA";

export { ADD_ITEM, CHANGE_SETTING, REPLACE_SETTINGS, INIT_DATA };
